name: 'Terraform Plan and Apply'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}


jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Login to Azure CLI
    - name: Azure login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Step 4: Initialize Terraform
    - name: Initialize Terraform
      run: terraform init

    # Step 5: Run Terraform Plan and Save Output
    - name: Terraform Plan and Save Output
      run: terraform plan -var-file="values.tfvars" -out=terraform.plan

    # Step 6: Upload the plan file as an artifact
    - name: Upload Terraform Plan Artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: terraform.plan

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      run: terraform init

    # Download the Terraform Plan Artifact
    - name: Download Terraform Plan Artifact
      uses: actions/download-artifact@v3
      with:
        name: terraform-plan # The name used in the upload step

    # Apply the Terraform Plan
    - name: Apply Terraform Plan
      run: terraform apply -auto-approve terraform.plan
      
